[[components]]
== COMPONENTS

=== Overview

This clause specifies the requirements classes that define the components to be used to define a Need.

A Need is a specific case of a Record and, therefore, complies with the relevant requirement classes of the https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records], taking into account the particular characteristics of the elements described in this section.

In this section, only the elements that differentiate the OGC API – Requirements from the https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records] are described.

[[need-item]]
=== Requirements Class "Need" (Component)

==== Overview

include::../requirements/requirements_class_need_item.adoc[]

The Need requirements class defines how the GONAR data model is combined with the Record data model described in section 7.2 of https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records]. The Need requirements Class defines the requirements for a _Need Item_. 
This requirements class follows the instructions described in recommendation /rec/record-core/extensions in section 7.2.3 of https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records].

Although this Standard does not mandate any particular encoding for a Need Item, a JSON encoding is proposed. Other encodings are allowed but are not described in this Standard.

[[need_item_props]]
==== Properties
The properties of a record that contains a `need` use the GONAR data model for the Need Item as described in section $$$7.2$$$ of OGC GONAR Standard: Data Model. The table <<tbl_record_need_item>> maps GONAR need properties with the properties defined in OGC API - Records section 7.2 in table 8 and table 9.

[#tbl_record_need_item,reftext='{table-caption} {counter:table-num}']
.Record properties mapped to need data model
[cols="25,45,35",options="header"]
|===
|Property in records|Obligation |Description |Property in need data model
|id |**required** |A unique record identifier assigned by the server |Id
|title |**required** |A human-readable name given to the resource described by this record. |Description
|geometry |optional |A spatial extent associated with the need described by this record. Can be null if there is no associated spatial extent |SubArea transformed to a geometry
|time |optional |A temporal extent associated with the need described by this record. Can be null if there is no associated temporal extent.	time |TemporalExtent
|conformsTo |optional |The extensions/conformance classes used by this record |"https://www.opengis.net/spec/ogcapi-requirements-1/1.0/conf/needs"
|externalIds |optional | One or more identifiers, assigned by an external products or to ISO 19113 product specifications, related to the need described by this record (if they already exist) | RelatedProductDescription as URL to the related product
|links |**required** (link to data requirement) |A list of links to data requirements and projects related to this record. |DataRequirement and Project
|===

The <<tbl_need_item>> provides an informative list of need properties that could not be mapped to the original record model and constitute and extension of the original record properties.

[#tbl_need_item,reftext='{table-caption} {counter:table-num}']
.Need Item extension
[cols="20,20,40",options="header"]
|===
|Property |Obligation | Description
|needType |**required** | Main purpose of the needs for in-situ data (see possible values in the GONAR data model)
|area |optional | Geographic scope or scale of the Need (see possible values in the GONAR data model)
|subarea |optional| Name of the specific geographical area, region, locality, or any topographical feature name related to the Need. The property `geometry` contains coordinates representing the subarea.
|processToRealize |optional | Process or set of tasks that are necessary to realize the Need.
|relatedProductDescription|optional | Description of a product to be created or the outcome to be achieved by using in-situ data as a result of the process. `externalIds` may be used to document identifiers (if they already exist).
|===

include::../requirements/need-item/mandatory-properties.adoc[]


[[needs-collection]]
=== Requirements Class "Needs Collection" (Component)

==== Overview

include::../requirements/requirements_class_needs_collection.adoc[]

The _Needs Collection_ requirements class is a specific implementation of the record collection defined in the https://docs.ogc.org/is/20-004r1/20-004r1.html#clause-record-collection[OGC API - Records Standard] (Section 7.3) that is applicable to collections that contains needs where a conformsTo property takes the value "https://www.opengis.net/spec/ogcapi-requirements-1/1.0/conf/needs" to indicate that all elements in the collection follow the <<need-item, need>> requirements.

include::../requirements/needs-collection/mandatory-properties.adoc[]

A _Needs Collection_ is an object that provides information about, and access to, a set of related <<need-item, needs>>.

[[data-requirement-item]]
=== Requirements Class "Data requirement" (Component)

==== Overview

include::../requirements/requirements_class_data_requirement_item.adoc[]

The Data Requirement class defines how the GONAR data model is combined with the Record data model described in section 7.2 of https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records]. The Data Requirement requirements Class defines the requirements for a _Data Requirement Item_. 
This requirements class follows the instructions described in recommendation /rec/record-core/extensions in section 7.2.3 of https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records].

Although this Standard does not mandate any particular encoding for a Data Requirement Item, a JSON encoding is proposed. Other encodings are allowed but are not described in this Standard.

[[data_requirement_item_props]]
==== Properties
The properties of a record that contains a `data requirement` use the GONAR data model for the Data Requirement Item as described in section $$$7.2$$$ of OGC GONAR Standard: Data Model. The table <<tbl_record_data_-_requirement_item>> maps GONAR data requirement properties with the properties defined in OGC API - Records section 7.2 in table 8 and table 9.

[#tbl_record_data_requirement_item,reftext='{table-caption} {counter:table-num}']
.Record properties mapped to data requirement data model
[cols="25,45,35",options="header"]
|===
|Property in records|Obligation |Description |Property in need data model
|id |**required** |A unique record identifier assigned by the server |Id
|title |**required** |A human-readable name given to the resource described by this record. |Name
|description |optional |A free-text description of the need described by this record. |Description
|themes |optional |A knowledge organization system used to classify the variable names described by this data requirement. |Variable and VariableDefinitionURL
|keywords |optional |A list of free-form names associated with the variable described by this data requirement. |Variable
|conformsTo |optional |The extensions/conformance classes used by this record |"https://www.opengis.net/spec/ogcapi-requirements-1/1.0/conf/requirements"
|externalIds |optional | One or more identifiers, assigned by an external dataset, that completely of partially matches the data requirement described by this record (if they already exist) | CompleteMatchingDataset or PartialMatchingDataset as URL to the related dataset
|links |**required** (link to data requirement) |A list of links to the need related to this record. |Need
|===

The <<tbl_data_requirement_item>> provides an informative list of data requirement properties that could not be mapped to the original record model and constitute and extension of the original record properties.

[#tbl_data_requirement_item,reftext='{table-caption} {counter:table-num}']
.Data Requirement Item extension
[cols="20,20,40",options="header"]
|===
|Property |Obligation | Description
|VariableClass |optional | 
|ThematicUncertainty |optional | 
|UoM |optional | 
|CoordinatedMeasure |optional | 
|UpdateFrequency |optional | 
|UpdateFrequencyUoM |optional | 
|Timeliness |optional | 
|TimelinessUoM |optional | 
|HorizontalResolution |optional | 
|HorizontalResolutionUoM |optional | DistanceUoMCode
|VerticalResolucion |optional | 
|VerticalResolutionUoM |optional | DistanceUoMCode
|EvenDistribution |optional | 
|DataAccess |optional | DataAccessCode
|CitSciAcceptance |optional | 
|reasonForPartialMatchings|optional | 
|===

include::../requirements/data-requirement-item/mandatory-properties.adoc[]


[[data-requirements-collection]]
=== Requirements Class "Data Requirement Collection" (Component)

==== Overview

include::../requirements/requirements_class_data_requirements_collection.adoc[]

The _Data Requirements Collection_ requirements class is a specific implementation of the record collection defined in the https://docs.ogc.org/is/20-004r1/20-004r1.html#clause-record-collection[OGC API - Records Standard] (Section 7.3) that is applicable to collections that contains data requirements where a conformsTo property takes the value "https://www.opengis.net/spec/ogcapi-requirements-1/1.0/conf/data-requirements" to indicate that all elements in the collection follow the <<data-requirement-item, data requirement>> requirements.

include::../requirements/data-requirements-collection/mandatory-properties.adoc[]

A _Data Requirements Collection_ is an object that provides information about, and access to, a set of related <<data-requirements-item, data requirements>>.

[[project-item]]
=== Requirements Class "Project" (Component)

==== Overview

include::../requirements/requirements_class_project_item.adoc[]

The Project requirements class defines how the GONAR data model is combined with the Record data model described in section 7.2 of https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records]. The Project requirements Class defines the requirements for a _Project Item_. 
This requirements class follows the instructions described in recommendation /rec/record-core/extensions in section 7.2.3 of https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records].

Although this Standard does not mandate any particular encoding for a Project Item, a JSON encoding is proposed. Other encodings are allowed but are not described in this Standard.

[[pProroject_item_props]]
==== Properties
The properties of a record that contains a `project` use the GONAR data model for the Project Item as described in section $$$7.2$$$ of OGC GONAR Standard: Data Model. The table <<tbl_record_project_item>> maps GONAR project properties with the properties defined in OGC API - Records section 7.2 in table 8 and table 9.

[#tbl_record_project_item,reftext='{table-caption} {counter:table-num}']
.Record properties mapped to project data model
[cols="25,45,35",options="header"]
|===
|Property in records|Obligation |Description |Property in project data model
|id |**required** |A unique record identifier assigned by the server |Id
|title |**required** |A free-text description of the need described by this record. |Description
|geometry |optional |A spatial extent associated with the need described by this record. Can be null if there is no associated spatial extent |SubArea transformed to a geometry
|time |optional |A temporal extent associated with the need described by this record. Can be null if there is no associated temporal extent.	time |TemporalExtent
|conformsTo |optional |The extensions/conformance classes used by this record |"https://www.opengis.net/spec/ogcapi-requirements-1/1.0/conf/needs"
|externalIds |optional | One or more identifiers, assigned by an external products or to ISO 19113 product specifications, related to the need described by this record (if they already exist) | RelatedProductDescription as URL to the related product
|links |**required** (link to data requirement) |A list of links to data requirements and projects related to this record. |DataRequirement and Project
|===

The <<tbl_project_item>> provides an informative list of project properties that could not be mapped to the original record model and constitute and extension of the original record properties.

[#tbl_project_item,reftext='{table-caption} {counter:table-num}']
.Project Item extension
[cols="20,20,40",options="header"]
|===
|Property |Obligation | Description
|needType |**required** | Main purpose of the needs for in-situ data (see possible values in the GONAR data model)
|area |optional | Geographic scope or scale of the Need (see possible values in the GONAR data model)
|subarea |optional| Name of the specific geographical area, region, locality, or any topographical feature name related to the Need. The property `geometry` contains coordinates representing the subarea.
|processToRealize |optional | Process or set of tasks that are necessary to realize the Need.
|relatedProductDescription|optional | Description of a product to be created or the outcome to be achieved by using in-situ data as a result of the process. `externalIds` may be used to document identifiers (if they already exist).
|===

include::../requirements/project-item/mandatory-properties.adoc[]


[[projects-collection]]
=== Requirements Class "Projects Collection" (Component)

==== Overview

include::../requirements/requirements_class_projects_collection.adoc[]

The _Projects Collection_ requirements class is a specific implementation of the record collection defined in the https://docs.ogc.org/is/20-004r1/20-004r1.html#clause-record-collection[OGC API - Records Standard] (Section 7.3) that is applicable to collections that contains projects where a conformsTo property takes the value "https://www.opengis.net/spec/ogcapi-requirements-1/1.0/conf/projects" to indicate that all elements in the collection follow the <<project-item, project>> requirements.

include::../requirements/projects-collection/mandatory-properties.adoc[]

A _Projects Collection_ is an object that provides information about, and access to, a set of related <<project-item, projects>>.



=== Encoding

[[json-component]]
==== Requirements Class "JSON" (Component)

===== Overview

include::../requirements/requirements_class_json.adoc[]

include::../requirements/json/fb-conformance.adoc[]

[[fb-item-encoding]]
===== Needs Item encoding

https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON] is a commonly used format based on JSON that is simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using a JSON-based format, supporting GeoJSON is recommended. 

The following requirements apply when:

. The API endpoint advertises conformance to the JSON Conformance Class.
. The client negotiates that the content of the server's response be https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON].

include::../requirements/json/fb-item-response.adoc[]

include::../requirements/json/fb-item-content.adoc[]

[NOTE]
======================================================================
OGC API - Feedback uses elements of ISO 19115 to define certain properties. Since ISO 19115 does not yet have an official JSON implementation, all references to this ISO in the feedback item JSON schema are made as '19115-4-core.json'.
======================================================================

[[schema_json_feedback]]
.link:https://github.com/opengeospatial/Geospatial-User-Feedback/tree/main/OGC_API/standard/openapi/schemas/ogcapi_feedback-item.yaml[Schema for a feedback item encoded as GeoJSON (ogcapi_feedback-item.yaml)]
[source,JSON]
----
include::../openapi/schemas/ogcapi_feedback-item.yaml[]
----

[[fb-collection-encoding]]
===== Needs Collection encoding

https://datatracker.ietf.org/doc/html/rfc8259[JSON] is an open standard file format and data interchange format that uses human-readable text to store and transmit data objects consisting of attribute–value pairs and arrays (or other serializable values).  JSON is a commonly used data encoding with diverse uses in electronic data interchange, including that of web applications with servers.

The following requirements apply when:

. The API endpoint advertises conformance to the JSON Conformance Class
. The client negotiates that the content of the server's response be JSON.

include::../requirements/json/fb-catalog-response.adoc[]

include::../requirements/json/fb-catalog-content.adoc[]

[NOTE]
======================================================================
The schema for the feedback collection is a specific implementation of the record collection defined in https://docs.ogc.org/DRAFTS/20-004.html#\_clause-core-record\_[OGC API - RecordsStandard].

While https://docs.ogc.org/DRAFTS/20-004.html#\_clause-core-record\_[OGC API - RecordsStandard] defines the property conformsTo as optional, OGC API - Feedback
considers it as required and its value is fixed as "http://www.opengis.net/spec/ogcapi-feedback-2/2.0/conf/feedback" to indicate that all elements in the collection follows the <<feedback_item, feedback item>> requirements.
======================================================================

.Schema for a collection record encoded as GeoJSON
link:https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordGeoJSON.yaml[]

