[[components]]
== COMPONENTS

=== Overview

This clause specifies the requirements classes that define the components to be used to define a Need Collection.

A Need Collection is a specific case of a Records Collection and, therefore, complies with the relevant requirement classes of the https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records], taking into account the particular characteristics of the elements described in this section.

In this section, only the elements that differentiate the OGC API – Requirements from the https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records] are described.

[[needs-item]]
=== Requirements Class "Collections" (Component)

==== Overview

include::../requirements/requirements_class_needs_item.adoc[]

The Need requirements class defines how the GONAR conceptual model is combined with the Record data model described in section 7.2 of https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records]. A _Need Item_ is the container of the actual needs.

The Need requirements Class defines the requirements for a _Need Item_, which is the atomic unit of information of a _Needs Collection_. It follows the instructions described in recommendation /rec/record-core/extensions in section 7.2.3 of https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records].

Although this Standard does not mandate any particular encoding for a Need Item or a Need Collection, a JSON encoding is proposed. Other encodings are allowed but are not described in this Standard.

[[fb_item_props]]
==== Properties
The properties of a record that contains needs uses the GONAR data model for the Needs Item $$$as described in section 7.2 of OGC GONAR Standard: Data Model$$$. The following table maps the properties defined in OGC API - Records section 7.2 with the GONAR Needs item. 

[#tbl_record_need_item,reftext='{table-caption} {counter:table-num}']
.Need Item
[cols="25,45,35",options="header"]
|===
|Property in records |Description |Property in needs item
|id |A unique record identifier assigned by the server |GONAR.itemIdentifier.code
|created |The date this record was created in the server |GUF_FeedbackItem.dateInfo.Data when GUF_FeedbackItem.dateInfo.dateType=="creation"
|updated |The most recent date on which the record was changed |GUF_FeedbackItem.dateInfo.Data when GUF_FeedbackItem.dateInfo.dateType=="revision"
|language |The language used for textual values (i.e., titles, descriptions, etc.) of this record |GUF_FeedbackItem.locale
|conformsTo |The extensions/conformance classes used in this record |"https://www.opengis.net/spec/ogcapi-requirements-1/1.0/conf/needs"
|externalIds |One or more identifiers, assigned by an external entity, for the resource described by this record |GUF_FeedbackItem.metadataIdentifier.code
|===

NOTE: The properties that https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API – Records] defines in table 9 for describing geospatial resources does not apply to this Standard because the objective of the GUF is not to describe the data but to provide additional information in addition to the metadata that the provider commonly facilitates. The only property that is useful for us it the externalIds, necessary to link tot the target of the feedback item.

The <<tbl_feedback_item>> provides an informative list of all properties that may be included in a User Feedback Item.

[#tbl_feedback_item,reftext='{table-caption} {counter:table-num}']
.User Feedback Item
[cols="20,20,40",options="header"]
|===
|Property | Requirement | Description
|itemIdentifier | **required** | Identifier for the feedback item
|abstract | **required** | Brief narrative description of this item, normally for display to a human
|purpose | optional| Summary of the intentions with which the feedback was provided
|contact | **required** | Information about the user providing feedback
|contactRole| **required** | User's role in the context of this feedback item
|dateInfo | **required** | Date when the feedback item was created, updated etc
|itemIsReplyTo | optional | Identifiers of one or more items of feedback to which this item is a response
|descriptiveKeywords | optional | Keywords that can be useful to search for this item. They are selected from controlled vocabularies
|tag | optional | Free text word that can be useful to search for this item
|locale | optional | Language and character set used within the feedback item
|externalFeedback | optional | Link to an item in an external repository that contains the feedback (not described inline)
|additionalQuality | optional | Structured quality assessment result
|userComment | optional | Text free user comment
|usage | optional | Structured usage report
|rating | optional | Rating code reflecting the satisfaction of the user with the resource used
|citation | optional | Citation of a published resource (e.g.: a report, a peer reviewed paper) that provides an evaluation of the usage of the resource
|additionalLineageSteps | optional | Additional lineage steps not included in the producer metadata
|significantEvent | optional | Significant natural events or sensor or platform anomalies that can affect the interpretation of the data
|target | **required** | Identifies a pre-existing resource (e.g., a dataset or a metadata record) from a catalogue
|===

include::../requirements/need-item/mandatory-properties.adoc[]


[[needs-collection]]
=== Requirements Class "Needs Collection" (Component)

==== Overview

include::../requirements/requirements_class_need_collection.adoc[]

The Need Collection requirements class is a specific implementation of the record collection defined in the https://docs.ogc.org/is/20-004r1/20-004r1.html#clause-record-collection[OGC API - Records Standard] (Section 7.3) that is applicable to collections that contains user feedback (a.k.a. feedback catalog) where a conformsTo property takes the value "http://www.opengis.net/spec/ogcapi-feedback-2/2.0/conf/feedback" to indicate that all elements in the collection follow the <<feedback_item, User Feedback Item>> requirements.

include::../requirements/feedback-collection/mandatory-properties.adoc[]

A _User Feedback Collection_ is an object that provides information about, and access to, a set of related <<feedback_item, User Feedback Items>>. Such a collection of User Feedbacks Items forms a user feedback catalog. 



[[feedback-query-parameters]]
=== Requirements Class "User Feedback Query Parameters" (Component)

==== Overview

The User Feedback Query Parameters requirements class is a specific implementation of the Record Core Query Parameters defined in the https://docs.ogc.org/is/20-004r1/20-004r1.html#clause-record-core-query-parameters[OGC API - Records Standard] (Section 7.4). It inherits all existing query parameters and extends the _externalIds_ query parameter behavior, and deprecates the _type_ parameter, since all elements in a User Feedback Collection are of the same type. 

[[query-parameters]]
==== Query parameters

[[query-parameters-externalIds]]
===== Parameter externalIds

include::../requirements/feedback-query-params/query_params_externalIds_def.adoc[]

include::../requirements/feedback-query-params/query_params_externalIds.adoc[]

In a _User Feedback Item_, externalIds refers to the identifier of the resource we are providing feedback on (the <<tbl_feedback_item,_target_>>). A single User Feedback Item can point to several externalIds.

_externalIds_ query parameter MAY contain a list of resource ids. This list can use different delimiters depending on the endpoint:

[#tbl_externalIds,reftext='{table-caption} {counter:table-num}']
.Accepted delimiters for the externalIds User Feedback Query parameter per endpoint
[cols="30,10,60",options="header"]
|===
|Endpoint |Delimiters accepted |Response
|/collections/{collectionsId}/items |"," | Only Feedback items with one or more of the specified external identifiers on the list SHALL appear in the response.
.3+|/collections/{collectionsId}/stats 
|"," | Returns n feedback summaries, one for each externalIds indicated on the list.
a| "\|" | Returns a single summary of those feedback items pointing to each one of the externalIds indicated on the list.
|"^" | Returns a single summary of those feedback items pointing at the same time to all the externalIds indicated on the list (feedback with multiple target).
|===


=== Encoding

[[json-component]]
==== Requirements Class "JSON" (Component)

===== Overview

include::../requirements/requirements_class_json.adoc[]

include::../requirements/json/fb-conformance.adoc[]

[[fb-item-encoding]]
===== Needs Item encoding

https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON] is a commonly used format based on JSON that is simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using a JSON-based format, supporting GeoJSON is recommended. 

The following requirements apply when:

. The API endpoint advertises conformance to the JSON Conformance Class.
. The client negotiates that the content of the server's response be https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON].

include::../requirements/json/fb-item-response.adoc[]

include::../requirements/json/fb-item-content.adoc[]

[NOTE]
======================================================================
OGC API - Feedback uses elements of ISO 19115 to define certain properties. Since ISO 19115 does not yet have an official JSON implementation, all references to this ISO in the feedback item JSON schema are made as '19115-4-core.json'.
======================================================================

[[schema_json_feedback]]
.link:https://github.com/opengeospatial/Geospatial-User-Feedback/tree/main/OGC_API/standard/openapi/schemas/ogcapi_feedback-item.yaml[Schema for a feedback item encoded as GeoJSON (ogcapi_feedback-item.yaml)]
[source,JSON]
----
include::../openapi/schemas/ogcapi_feedback-item.yaml[]
----

[[fb-collection-encoding]]
===== Needs Collection encoding

https://datatracker.ietf.org/doc/html/rfc8259[JSON] is an open standard file format and data interchange format that uses human-readable text to store and transmit data objects consisting of attribute–value pairs and arrays (or other serializable values).  JSON is a commonly used data encoding with diverse uses in electronic data interchange, including that of web applications with servers.

The following requirements apply when:

. The API endpoint advertises conformance to the JSON Conformance Class
. The client negotiates that the content of the server's response be JSON.

include::../requirements/json/fb-catalog-response.adoc[]

include::../requirements/json/fb-catalog-content.adoc[]

[NOTE]
======================================================================
The schema for the feedback collection is a specific implementation of the record collection defined in https://docs.ogc.org/DRAFTS/20-004.html#\_clause-core-record\_[OGC API - RecordsStandard].

While https://docs.ogc.org/DRAFTS/20-004.html#\_clause-core-record\_[OGC API - RecordsStandard] defines the property conformsTo as optional, OGC API - Feedback
considers it as required and its value is fixed as "http://www.opengis.net/spec/ogcapi-feedback-2/2.0/conf/feedback" to indicate that all elements in the collection follows the <<feedback_item, feedback item>> requirements.
======================================================================

.Schema for a collection record encoded as GeoJSON
link:https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordGeoJSON.yaml[]

