== SCOPE
//The OGC API - Feedback Standard specifies requirement classes for manage descriptive information provided by users (user feedback) about geospatial resources.
The OGC API - Requirements Standard specifies _requirement classes_ for manage _needs_ and _data requirements_ (technical descriptions) provided by users about target geospatial resources. In this context:

* A need (i.e. a problem or issue to be addressed by using geospatial data) is an item of the first possible collection type (the equivalent to a catalogue) within the OGC API - Requirements Standard.

* A data requirement (i.e. a concrete technical description of the properties of a potential geospatial dataset that will fulfil the need) is an item of the second possible collection type (the equivalent to a catalogue) within the OGC API - Requirements Standard.

NOTE: The modular specification divides the standards into requirements classes that contain 1 or more requirements/recommendations/permissions. Please do not confuse _standard requirements_ with _data requirements_ (this later are the ones under the scope of this Standard). 

Needs and requirements are provided by the users of geospatial data. Commonly the user contributing needs and requirements are authenticated and known by the API Implementation. However, the description of the user and its contact details are subjected to privacy protection laws (in europe GDPR) and its definition are not part of the scope of this Standard.

* A project (i.e. the context where the need is generated) is an item of the third possible collection (the equivalent to a catalogue) within the OGC API - Requirements Standard. They are grouped into data requirement collections.

The level of detail of the needs and data requirements defines the observed property and some characteristics of the data, including spatial and temporal extent, uncertainty and timelines. It is not in the scope of the needs and requirements data model to fully specify a product the fulfils the user needs. The data user can cooperate with data provides to fully specify a product following the ISO 19131.

A need can be translated into 1 or more user requirements (relation 1..*). A project can be associated to many needs (and indirectly, to 1 or many data requirements).

The OGC API - Requirements Standard uses and extends on OGC API - Records to describe how needs, data requirements and project collections can be crawled or searched. Crawling a collection involves following embedded links from one item (in a collection) to the next item. Searching a collection of items involves specifying query predicates that retrieves a subset of items.
