== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of OGC 06-121r9 [1], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard. It also uses definitions from the first version of the conceptual model OGC 15-097r1:2016 [7].

For the purposes of this document, the following additional terms and definitions apply.

=== data requirement
specific technical characteristics of the in-situ observations needed to deliver a reliable geospatial product or service that may or may not exist yet.

NOTE: The ISO 19158:2025 defines the term "specified requirement" as "need or expectation that is stated" that can be considered an equivalent concept.

=== matching data
observational data that meets completely or partially the data requirements.

NOTE: The ISO 19158:2025 defines the term "conformance" as "fulfillment of a requirement" that can be considered an equivalent concept.

=== need
a problem or an issue to be addressed by using in-situ observational data.

=== process
set of interrelated or interacting activities that use inputs to deliver an intended result

NOTE: The aim of the process is to fulfill the need. 

NOTE: In the context of this Standard, in order to execute the process activities, observational data is required.

SOURCE: ISO 19158:2025

=== project
context in which needs and requirements are originated and processes are executed to fulfill the needs and deliver the intended results. Data requirements are derived from the scope and objectives of a project and they condition the feasibility of the intended results of the project. Commonly, projects have an starting activity devoted to analyze project needs and data requirements. Other activities in the project may look for observational data that matches completely or partially the requirements and may need other activities to produce the data required.

//=== item
//anything that can be described and considered separately.
//[.source]
//<<ISO19157:2013>>

//=== quality
//degree to which a set of inherent characteristics fulfils requirements.
//[.source]
//<<ISO9000:2005>>

//=== metadata
//information about a resource.
//[.source]
//<<ISO19115-1:2014>>

//=== user
//consumer of a resource.
//[.source]
//<<OGC15-097r1>>




