== Scope

The "OGC Geospatial Observations Needs and Requirements (GONAR) Standard: Data Model" defines the data model for encoding user needs and data requirements about observational data. This Standard is inspired by the ISO 19131 data model and the ISO 19115 data model and uses them whereas possible. This Standard describes three requirement classes for needs, data requirements to fulfil the needs, and projects where the needs emerge. 

This OGC Standard is defined to support implementation of clients that are able to capture and exchange data requirements of geospatial data. Clients implementing this Standard can provide a user interface to allow for encoding needs and requirements descriptions and to present this information in a database. In addition, this OGC Standard is applicable to servers that store data requirements information. Clients and servers can exchange data requirements with an API that uses the data model defined in this Standard

While, this Standard neither defines an encoding nor a query language to request or exchange requirements with other systems, it can be the bases for other standards doing so. Commonly, the data required is processed to extract the necessary information and knowledge to fulfill the needs. Detail descriptions of the necessary process to fulfil the needs are out of scope of this Standard. While this Standard introduces the concept of project, projects are not described in full and are only considered as a means of filtering and subsetting. While the whole model is user oriented this standard does not provide a means to describe data users as the description of users can easily include confidential information.



