[obligation=informative]
=== Geospatial Observations, Needs and Requirements

Understanding data requirements from users is a crucial initial step for producing data that fits its intended purpose. However, data providers often create geospatial datasets based on what they believe are feasible and useful, with characteristics described in product specifications, but those providers might not completely know the real needs of their users, resulting in reduced effective utilization of data. In contrast, user requirements for data can be collected and utilized to define and provide a single data product or can be used to define a collection of datasets that cover a particular thematic domain. This way, when a user requirement for observations cannot be covered with existing datasets or product specifications (e.g., air quality data is not updated every hour, so a pollutant plume cannot be tracked), data producers can fill the gaps in the current data products by deploying new sensors and extend their product specifications to satisfy user needs (e.g., a new Air quality dataset is produced every hour, just in case a pollution plume needs to be tracked), and potentially to find new markets for their data.

For the purpose of this Standard, _Data requirements_ (understood as specific technical characteristics of a in-situ observation collection  that may or may not exist yet and provided by data users to fulfill a _need_ and in the context of a _project_) shall be distinguished from Standard requirements (the modular specification divides the standards into requirements classes that contains 1 or more requirements/recommendations/permissions). 

Within GONAR, data requirements are described in the context of a project participated by a user or a community of users working towards achieving the project objectives. A project can have one or more needs, which can be translated into one or more data requirements that will be used in data processing to fulfil the needs

The GONAR model is designed to be as simple as possible but comprehensive enough. Following are examples of questions that the GONAR model covers:

* What is the purpose or need that motivates a particular data requirement?
* What types of needs (e.g., scientific research, decision making, policy monitoring) are being addressed by a given project?
* What geographic area and temporal extent are associated with a specific need?
* What products or outcomes are expected from addressing a particular need?
* What methods or tasks are necessary to realize the need?
* Which variables are required to address a given need?
* What horizontal and vertical resolution are required for a particular variable?
* What timeliness and update frequency are required for a particular variable?
* Which methods of data access are acceptable for fulfilling the need?
* Is citizen science data considered acceptable for addressing a given need?
* Which data requirements are shared by multiple needs or projects?
* How much the data requirements differ between two projects addressing similar problems?

When combined with a catalogue of existing datasets or observational resources, the GONAR model can also support answer questions such as:

* Which datasets meet the data requirements?
* Which data requirements cannot currently be met by the available datasets?
* Which are the common barriers to discover, access and reuse of existing data that fulfil the requirements?
* Which are the characteristics that a dataset should improve to fulfil completely the data requirements?

=== Connection to the ISO TC 211 standard family

The GONAR Standard reuses elements and concepts defined in [ISO19131]. This ISO standard forms the basis of a data model that defined the characteristics that are useful for describing data products specifications from the data producer perspective. Elements were added to represent the user perspective.

Whenever possible, GONAR also reuses elements defined in [ISO19115]. While ISO 19115 it is intended to describe geospatial metadata for existing datasets, GONAR focuses on describing the characteristics of datasets before they were identified. Some elements of the ISO 19115 that are applicable to describing data requirements are reused.
